options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ravensoulwellness', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ravensoulwellness']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'ravensoulwellness'
      - '--image'
      - 'gcr.io/$PROJECT_ID/ravensoulwellness'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-west2'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/ravensoulwellness'